version: 2.1
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress dependencies
    - image: cypress/base:12.14.0
      environment:
        ## this enables colors in the output
        TERM: xterm
        NODE_OPTIONS: --max_old_space_size=4096

commands:
  restore-cache-and-install-dependencies:
    description: "Restore cache and install dependencies"
    steps:
      - restore_cache:
          key: v2-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
  publish_to_expo:
    description: "Publish JS bundle to Expo"
    steps:
      - checkout
      - restore-cache-and-install-dependencies
      - run:
          name: Publish to Expo
          command: |
            EXPO_RELEASE_CHANNEL_NAME=${EXPO_RELEASE_CHANNEL/*\//}
            npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL_NAME

jobs:
  publish_feature_to_expo:
    <<: *defaults
    environment:
      EXPO_RELEASE_CHANNEL: <<pipeline.git.branch>>
    resource_class: xlarge
    steps:
      - publish_to_expo

  publish_to_expo_staging:
    <<: *defaults
    environment:
      EXPO_RELEASE_CHANNEL: staging
    resource_class: xlarge
    steps:
      - publish_to_expo

  publish_to_expo_production:
    <<: *defaults
    environment:
      EXPO_RELEASE_CHANNEL: production
    resource_class: xlarge
    steps:
      - publish_to_expo

workflows:
  version: 2
  build-deploy:
    jobs:
      - publish_feature_to_expo:
          context: tic-tac-toe-feature

          filters:
            branches:
              ignore: main
      - publish_to_expo_staging:
          context: tic-tac-toe-staging

          filters:
            branches:
              only: main

      - publish_to_expo_production:
          context: tic-tac-toe-prod

          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
